### ISSUE TITLE
Update to latest dry-validation

### ISSUE THREAD

**Issue by timriley** [icelab/formalist#25]
And adjust our `CollectionRulesCompiler` depending on whether `:set` remains in dry-validation's rules AST (pending clarification in dryrb/dry-validation#58).

**Comment by solnic** [comment]
`:set` rules are still there, it's just that they don't mean something is a nested structure, there should be another way of detecting that rules describe a nested structure which I should figure out :)

**Comment by timriley** [comment]
Thanks for the info, @solnic.

I'll use this issue to give you a rundown of the key places we integrate with dry-validation.

**rules**

We consume its rules AST ([form.rb#L37](https://github.com/icelab/formalist/blob/master/lib/formalist/form.rb#L37)) and pass it around to each element as we build the form. Each element will interrogate the rules as appropriate and build up a simplified predicates array that we include with the elements in our AST.

Our most complex work with the rules is in the elements that act as containers for other nested elements, e.g. [`many`](https://github.com/icelab/formalist/blob/master/lib/formalist/elements/many.rb) and [`attr`](https://github.com/icelab/formalist/blob/master/lib/formalist/elements/attr.rb). These need to pull out two sets of rules:

1. any rules that apply to themselves as containers directly (e.g. rules applying to the hash or array)
2. any rules that apply to their children

They fetch the rules that apply to their containers using the [`ValueRulesCompiler`](https://github.com/icelab/formalist/blob/master/lib/formalist/validation/value_rules_compiler.rb), and the rules for their children using the [`CollectionRulesCompiler`](https://github.com/icelab/formalist/blob/master/lib/formalist/validation/collection_rules_compiler.rb).

Once any element has an appropriately targeted set of rules, it uses the [`PredicateListCompiler`](https://github.com/icelab/formalist/blob/master/lib/formalist/validation/predicate_list_compiler.rb) to reduce them down to the simplified form we include in our AST, e.g.

```ruby
[:and, [[:predicate, [:gteq?, [1]]], [:predicate, [:lteq?, [10]]]]]
```

**messages**

We're now pulling the messages from a `Dry::Validation::Schema::Result` object passed to the form (see [result.rb#L18](https://github.com/icelab/formalist/blob/master/lib/formalist/form/result.rb#L18)). We then pass the messages object around to each element as we build the form and they need to pull out the relevant messages for including in their AST representation (messages here are just an array of strings).

In most cases, this is relatively straightforward (look for where we're assigning `@errors =` in any part of the codebase), but we still have to do a bit of hoop-jumping to isolate the strings from dry-v's messages object structure. The most complex example would be in [many.rb#L141-L149](https://github.com/icelab/formalist/blob/master/lib/formalist/elements/many.rb#L141-L149), where we need to fetch the errors that apply to each specific object in a collection of nested objects.

**current status**

Right now we have [validation_spec.rb](https://github.com/icelab/formalist/blob/master/spec/integration/validation_spec.rb) to serve as a test to make sure we're integrating properly. If you look at the spec, you should be able to identify the things I've talked about above (the predicate lists and the error messages distributed throughout the form). You should also note that there's 2 parts commented out due to the `:set` elements missing from dry-v's AST for nested validations. It'd be great to get those working again.

If you're up for helping to get formalist on the latest dry-validation, I'd really appreciate it! Otherwise, I'd still be very happy to receive any suggestions you might have :)

**Comment by timriley** [comment]
We've updated to the latest dry-validation by no longer requiring it anymore :joy:
