### ISSUE TITLE
Allow easier exiting of blockquotes style in text editor

### ISSUE THREAD

**Issue by tobydallder** [icelab/formalist#52]
When selecting the blockquote style and entering text, pressing return creates a new blockquote on a new line below. Pressing enter on an empty blockquote creates the empty blockquote and also adds a new blockquote below that on another line. The only way to break out of this is by manually selecting a new style to overwrite repeated blockquote.

Replicating the behaviour currently in place with list items where returning an empty line item breaks out of the list style and returns to the default paragraph style would be nicer. 

Edit: This also applies to pullquotes. And do we need support paragraph breaks in block/pullquotes?

**Comment by timriley** [comment]
Copied to https://github.com/icelab/formalist-standard-react/issues/104
