### ISSUE TITLE
Allow date fields to be unset

### ISSUE THREAD

**Issue by andrewcroome** [icelab/formalist#54]
Date selections aren't able to be removed once set (at least for me). When removing the content of the field, the old date is still persisted.

<img width="1331" alt="screen shot 2016-12-08 at 2 53 48 pm" src="https://cloud.githubusercontent.com/assets/3338621/20997166/25aa24be-bd57-11e6-9c42-c1dcd10e1f1b.png">

**Comment by timriley** [comment]
Moved to https://github.com/icelab/formalist-standard-react/issues/103
