### ISSUE TITLE
Define local field types in a form with specific configuration

### ISSUE THREAD

**Issue by timriley** [icelab/formalist#9]
Related to #8, there's another kind of form-level field type configuration we'd want to do. Say we have an "image" field that's used in different places, but in a couple of different ways, each requiring different configuration.  We could support this by allowing the field to be "defined" locally on the form with different configurations. Something like this:

```ruby
class MyClass < Formalist::Form
  define_field :author_image, from: :image do |author_image_config|
    author_image_config.search_api_url = "/images/authors.json"
  end

  define_field :cover_image, from: :image do |cover_image_config|
    cover_image_config.search_api_url = "/images/covers.json"
  end

  many :author_images do |images|
    images.field :image, type: :author_image
  end

  field :front_cover_image, type: :cover_image
  field :back_cover_image, type: :cover_image
end
```

**Comment by timriley** [comment]
I think we already support whaNow that we have general-purpose element attributes, as well as a container for form elements, and form elements can be subclassed, I don't think we need special API to extend a field's configuration anymore.

We could simply do this:


```ruby
class MyForm < Formalist::Form
  class AuthorImage < MyApp::FormElements::Image
    configure do |config|
      config.search_api_url = "/images/authors.json"
    end

    configure.config

**Comment by timriley** [comment]
I think we already support what I wanted to do here.

Now that form elements have general attributes, we could just override them per-field where needed, e.g.

```ruby
class AuthorImage < Formalist::Elements::Field
  attribute :search_api_url, Types::Strict::String, "/images/authors.json"
end

Formalist::Elements.register :author_image, AuthorImage

class MyForm < Formalist::Form
  define do
    author_image :image_url, search_api_url: "/images/somewhere_else.json"
  end
end
```

And if we needed even _deeper_ per-form customisation, we have a lot of options now that we can subclass form elements and register a dedicated elements container per-form:

```ruby
class MyForm < Formalist::Form
  class AuthorImage < MyApp::FormElements::AuthorImage
    # any custom code you want here
  end

  configure do |config|
    config.elements_container = Class.new(Formalist::Elements) do
      register :special_author_image, AuthorImage
    end
  end

  define do
    special_author_image :image_url
  end
end
```

This latter approach is a little awkward, but I don't think it'd be needed very often, so I don't think it's worth complicating the library by building dedicated API for this until we _really_ think it's needed. Closing for now.

**Comment by blelump** [comment]
Hi @timriley !

Thanks for pointing this out. Let me ask, according to the specs, the formalist job is to built an AST based upon schema definition (`Formalist::Form`) and data provided by `dry-v`? Then I believe, it needs a renderer which would consume the AST and return an output. Assuming this is a backend job, it would be e.g.  a HTML output. Am I right?

**Comment by timriley** [comment]
@blelump You're exactly right. We've been building a JavaScript-based renderer to start with. See:

* https://github.com/icelab/formalist-compose
* https://github.com/icelab/formalist-standard-react
* https://github.com/icelab/formalist-serialize-react

Later on I'd imagine it'd be great to have one (or more) Ruby-based renderers generating form HTML from the server-side, too.

I apologise if the documentation is sketchy right now – the libraries are all still under heavy development. We'll be documenting things a little more fully once everything's settled.

**Comment by blelump** [comment]
@timriley , thanks!

Many solutions of Formalist 'smells' like `dry-rb` ones, I like that :smile: .
